### ISSUE TITLE
What is the right command to repack the PAK archives?

### ISSUE THREAD

**Issue by AEBus** [wetor/LucaSystemTools#9]
Hello, what is the right command to repack the PAK archives?
When I try this kind of command: **LucaSystemTools -t pak -m import -f wrk -o rdy** pops up a bunch of errors.
```
D:\wrk\LucaSystemTool>LucaSystemTools -t pak -m import -f wrk -o rdy
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\wrk\LucaSystemTool\wrk\SCRIPT_unpacked\SEEN0513'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ProtPak.PAKManager.Pack(String file) in D:\wrk\LucaSystemTool\src\lben\LucaSystemTools\PakTools.cs:line 91
   at ProtPak.PAKManager.FileImport(String path, String outpath) in D:\wrk\LucaSystemTool\src\lben\LucaSystemTools\PakTools.cs:line 227
   at LucaSystem.Utils.CommandLineUtil.OnExecute() in D:\wrk\LucaSystemTool\src\lben\LucaSystemTools\Utils\CommandLineUtil.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at LucaSystemTools.Program.Main(String[] args) in D:\wrk\LucaSystemTool\src\lben\LucaSystemTools\Program.cs:line 17
```

The following folders and files are in the wrk folder:
```
\wrk\SCRIPT.PAK_unpacked\
\wrk\SCRIPT.PAK.pakhead
\wrk\SCRIPT.PAK
```

**Comment by AEBus** [comment]
Ow, when i replaced
```C#
string out_file = Path.Combine(Path.GetDirectoryName(file), Path.GetFileNameWithoutExtension(file));
```
with
```C#
string out_file = Path.Combine(Path.GetDirectoryName(file), Path.GetFileName(file));
```
In **PakTools.cs**, hen renamed SCRIPT.PAK.pakhead into SCRIPT.PAK
A command LucaSystemTools -t pak -m import -f SCRIPT.PAK work without errors.
When i need repack a multiple files, i use a command LucaSystemTools -t pak -m import -f wrk -o wrk, then all PAK files in folder repacked.
